FROM node:24-alpine

WORKDIR /app

COPY . .

CMD ["node", "main.js"]

EXPOSE 8080

# To build the Docker image, run: docker build -t basic_js .
# To run the Docker container, use: docker run -p 8080:8080 basic_js